layout: stacked
style: light
#layout: sidebar
#style: dark


# donot compile those files
exclude:
  - README.md
  - original_README.md
  - clean_files.sh
  - start_server.sh
  - github-readme.md


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

future: true #show post dated in a future date
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
     - photo-cell
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
    facebook: efcieorg
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: 240155787
  # unsplash: your_username
  # vk: your_username
    website: https://www.efcie.org/
    youtube: ZhangDanFanClub

topics:
  - name: 在线圣经
    web_url: http://www.bbintl.org/bible/read/?lang=gb&ref=DT&ch=1&bkref=gb&t=N&sname=Luk&b=%E8%B7%AF%E5%8A%A0%E7%A6%8F%E9%9F%B3
    image_url: http://www.bbintl.org/bible/img/bible7.gif
  - name: 公众号-溪边树
    web_url: https://open.weixin.qq.com/qr/code?username=Faith-Hope-Love-365
    image_url: https://open.weixin.qq.com/qr/code?username=Faith-Hope-Love-365

slideshow:
#  - src: shengxiaomei-concert.jpeg
#    alt: Coming SOON! Concert by Sheng Xiaomei
#    href: 2020/03/14/news-xiaomeisheng-concert
  - src: efc-27th.jpg
    alt: 27th Anniversary of EFCIE
  - src: choir.jpg
    alt: 唱诗班
  - src: easter2019.jpg
    alt: 复活节
  - src: party.jpg
    alt: 聚会
  - src: dinner.jpg
    alt: 聚会
  